# Generated by Django 4.1 on 2022-08-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_surname', models.TextField()),
                ('customer_dni', models.IntegerField(db_column='customer_DNI')),
                ('dob', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField()),
                ('iban', models.TextField()),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionesCliente',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField()),
                ('street_number', models.IntegerField(blank=True, null=True)),
                ('city', models.TextField()),
                ('region', models.TextField()),
                ('country', models.TextField()),
                ('customer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'direcciones_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionesEmpleado',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField()),
                ('street_number', models.IntegerField(blank=True, null=True)),
                ('city', models.TextField()),
                ('region', models.TextField()),
                ('country', models.TextField()),
                ('employee_id', models.IntegerField()),
            ],
            options={
                'db_table': 'direcciones_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionesSucursal',
            fields=[
                ('branch_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField(blank=True, null=True)),
                ('street_number', models.IntegerField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'direcciones_sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('employee_hire_date', models.TextField()),
                ('employee_dni', models.IntegerField(db_column='employee_DNI')),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarcaTarjetas',
            fields=[
                ('creditcardbrand_id', models.AutoField(primary_key=True, serialize=False)),
                ('creditcardbrand_name', models.TextField()),
            ],
            options={
                'db_table': 'marca_tarjetas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.TextField()),
                ('loan_date', models.TextField()),
                ('loan_total', models.IntegerField()),
            ],
            options={
                'db_table': 'prestamo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.BinaryField()),
                ('branch_name', models.TextField()),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_pan', models.TextField()),
                ('card_cvv', models.IntegerField()),
                ('valid_from', models.TextField()),
                ('valid_thru', models.TextField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('customer_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_description', models.TextField()),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('account_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_description', models.TextField()),
            ],
            options={
                'db_table': 'tipo_cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('cardtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('cardtype_description', models.TextField()),
            ],
            options={
                'db_table': 'tipo_tarjeta',
                'managed': False,
            },
        ),
    ]
